# Generated by Django 3.2.4 on 2021-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoliste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='n_employees',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2 - 9'), (10, '10 - 49'), (50, '50 - 249'), (250, '250 - 999'), (1000, '1000 - 4999'), (5000, '5000+')], null=True, verbose_name="Nombre d'employés"),
        ),
    ]
