# Generated by Django 3.2.4 on 2021-06-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoliste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Prénom')),
                ('surname', models.CharField(max_length=50, verbose_name='Nom de famille')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('phone1', models.CharField(max_length=25, verbose_name='Téléphone 1')),
                ('phone2', models.CharField(max_length=25, verbose_name='Téléphone 2')),
                ('mail', models.EmailField(max_length=254, verbose_name='Adresse mail')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ecoliste.enterprise', verbose_name='Entreprise')),
            ],
        ),
    ]
