# Generated by Django 3.2.4 on 2021-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoliste', '0002_contacts_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, verbose_name='Téléphone 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25, verbose_name='Téléphone 2'),
            preserve_default=False,
        ),
    ]
