# Generated by Django 3.2.4 on 2021-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoliste', '0002_nemployees_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='annual_sales',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '< 2 millions €'), (2, '2 à 10 millions €'), (3, '10 à 50 millions €'), (4, '50 à 200 millions €'), (5, '200 à 1500 millions €'), (6, '> 1500 millions €')], null=True, verbose_name="Chiffre d'affaires"),
        ),
    ]
