# Generated by Django 3.2.4 on 2021-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoliste", "0003_contacts_fix_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="website",
            field=models.URLField(blank=True, db_index=True, verbose_name="Site web"),
        ),
    ]
